# ANN Lab 2 — NumPy Vectors & Matrices

**Name:** Arham Tahir
**Registration:** FA23-BAI-027

This notebook covers 9 tasks on NumPy fundamentals: vectors, matrices, arithmetic operations, dot products, reshaping, indexing, slicing, random matrices, and transposition. Each task has a short explanation followed by working code.

In [1]:
import numpy as np

## Task 1: Vectors

We create a vector of ages for 6 people, inspect its shape/dimensions/data type, compute "years until retirement" without a loop (vectorized subtraction), and find the average age using `np.mean()`.

In [2]:
# Vector of ages for 6 people
ages = np.array([25, 30, 45, 52, 38, 60])

print("Ages vector:", ages)
print("Shape:", ages.shape)
print("Dimensions (ndim):", ages.ndim)
print("Data type:", ages.dtype)

Ages vector: [25 30 45 52 38 60]
Shape: (6,)
Dimensions (ndim): 1
Data type: int64


In [3]:
# Years until retirement (65 - age), computed without a loop (vectorized operation)
years_until_retirement = 65 - ages
print("Years until retirement:", years_until_retirement)

Years until retirement: [40 35 20 13 27  5]


In [4]:
# Average age using a NumPy function (not manual calculation)
average_age = np.mean(ages)
print("Average age:", average_age)

Average age: 41.666666666666664


## Task 2: Matrices

We build a 4×3 matrix of sales (4 products × 3 months), inspect its shape and total element count, create a same-shaped zero matrix using `np.zeros()`, and replace its second row using indexing.

In [5]:
# 4x3 matrix: rows = products, columns = months
sales = np.array([
    [120, 150, 130],   # Product 1
    [80,  90,  100],   # Product 2
    [200, 210, 190],   # Product 3
    [60,  75,  70]     # Product 4
])

print("Sales matrix:\n", sales)
print("Shape:", sales.shape)
print("Total number of elements:", sales.size)

Sales matrix:
 [[120 150 130]
 [ 80  90 100]
 [200 210 190]
 [ 60  75  70]]
Shape: (4, 3)
Total number of elements: 12


In [6]:
# Same-shaped matrix filled with zeros using a NumPy function
zero_matrix = np.zeros(sales.shape)
print("Zero matrix:\n", zero_matrix)

Zero matrix:
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [7]:
# Replace the second row (index 1) using indexing, not recreation
zero_matrix[1] = [10, 20, 30]
print("Updated matrix:\n", zero_matrix)

Updated matrix:
 [[ 0.  0.  0.]
 [10. 20. 30.]
 [ 0.  0.  0.]
 [ 0.  0.  0.]]


## Task 3: Addition & Subtraction

We create two 3×3 matrices for marks of 3 students in 3 subjects across Term 1 and Term 2, compute the combined total and the improvement, then use code (not manual reading) to find the student with the highest total improvement.

In [8]:
# Rows = students, Columns = subjects
term1 = np.array([
    [70, 65, 80],   # Student 1
    [55, 60, 58],   # Student 2
    [90, 85, 88]    # Student 3
])

term2 = np.array([
    [75, 70, 85],   # Student 1
    [65, 72, 60],   # Student 2
    [92, 80, 95]    # Student 3
])

print("Term 1 marks:\n", term1)
print("Term 2 marks:\n", term2)

Term 1 marks:
 [[70 65 80]
 [55 60 58]
 [90 85 88]]
Term 2 marks:
 [[75 70 85]
 [65 72 60]
 [92 80 95]]


In [9]:
# Total combined marks for each student in each subject
total_marks = term1 + term2
print("Total combined marks:\n", total_marks)

Total combined marks:
 [[145 135 165]
 [120 132 118]
 [182 165 183]]


In [10]:
# Improvement (Term2 - Term1) for each student in each subject
improvement = term2 - term1
print("Improvement matrix:\n", improvement)

Improvement matrix:
 [[ 5  5  5]
 [10 12  2]
 [ 2 -5  7]]


In [11]:
# Identify the student with the highest total improvement using code
student_improvement_totals = improvement.sum(axis=1)   # sum across subjects for each student
best_student_index = np.argmax(student_improvement_totals)

print("Total improvement per student:", student_improvement_totals)
print(f"Student with highest improvement: Student {best_student_index + 1} "
      f"(total improvement = {student_improvement_totals[best_student_index]})")

Total improvement per student: [15 24  4]
Student with highest improvement: Student 2 (total improvement = 24)


## Task 4: Dot Product

We compute a total bill using the dot product of prices and quantities, then extend this to two customers at once using matrix–vector dot product.

In [12]:
# Prices of 4 items and quantities purchased
prices = np.array([50, 20, 15, 100])
quantities = np.array([2, 5, 3, 1])

# Total bill using dot product (not manual multiply+add)
total_bill = np.dot(prices, quantities)
print("Total bill:", total_bill)

Total bill: 345


In [13]:
# 2x4 matrix: rows = customers, columns = quantities of each of the 4 items
customers_quantities = np.array([
    [2, 5, 3, 1],   # Customer 1
    [1, 2, 4, 3]    # Customer 2
])

# Total bill for both customers using a single dot product operation
total_bills = customers_quantities.dot(prices)
print("Total bill for each customer:", total_bills)

# Explanation:
# customers_quantities has shape (2,4) and prices has shape (4,).
# For a dot product (matrix-vector multiplication) to work, the number of
# COLUMNS of the first array (4) must match the number of elements (length)
# of the second array/vector (4). Each row of customers_quantities is
# "matched up" element-by-element with the prices vector and summed,
# which is only mathematically valid when these inner dimensions agree.
# That's why the last dimension of customers_quantities (4 items) had to
# equal the length of the prices vector (4 items).

Total bill for each customer: [345 450]


## Task 5: Reshaping

We create a 1D array of 12 values (hours studied over 12 days), reshape it into a 4×3 matrix (4 weeks × 3-day study plan), reshape it into another valid shape, and then deliberately try an invalid reshape to observe the error.

In [14]:
# 1D array of hours studied over 12 days
hours_studied = np.array([2, 3, 1, 4, 2, 5, 3, 1, 2, 4, 3, 2])
print("Original 1D array:", hours_studied)
print("Original shape:", hours_studied.shape)

Original 1D array: [2 3 1 4 2 5 3 1 2 4 3 2]
Original shape: (12,)


In [15]:
# Reshape into 4 rows x 3 columns (4 weeks of a 3-day study plan)
reshaped_4x3 = hours_studied.reshape(4, 3)
print("Reshaped to 4x3 (4 weeks x 3 days):\n", reshaped_4x3)

Reshaped to 4x3 (4 weeks x 3 days):
 [[2 3 1]
 [4 2 5]
 [3 1 2]
 [4 3 2]]


In [16]:
# Reshape into a different valid shape, e.g. 3x4 (3 weeks x 4 days)
reshaped_3x4 = hours_studied.reshape(3, 4)
print("Reshaped to 3x4 (3 weeks x 4 days):\n", reshaped_3x4)

print("\nBoth reshaped versions:")
print("4x3 version:\n", reshaped_4x3)
print("3x4 version:\n", reshaped_3x4)

Reshaped to 3x4 (3 weeks x 4 days):
 [[2 3 1 4]
 [2 5 3 1]
 [2 4 3 2]]

Both reshaped versions:
4x3 version:
 [[2 3 1]
 [4 2 5]
 [3 1 2]
 [4 3 2]]
3x4 version:
 [[2 3 1 4]
 [2 5 3 1]
 [2 4 3 2]]


In [17]:
# Try an invalid reshape (5x3 = 15 elements, but we only have 12) to see the error
try:
    invalid_reshape = hours_studied.reshape(5, 3)
except ValueError as e:
    print("Error message received:")
    print(e)

# Note: The error occurs because 5 x 3 = 15, but the original array only has
# 12 elements. NumPy requires the total number of elements to stay the same
# before and after reshaping.

Error message received:
cannot reshape array of size 12 into shape (5,3)


## Task 6: Indexing

We generate a 5×5 matrix of random integers between 1 and 50, access specific elements using positive and negative indexing, and modify an element in place.

In [18]:
np.random.seed(1)  # for reproducibility
matrix_5x5 = np.random.randint(1, 51, size=(5, 5))
print("5x5 random integer matrix:\n", matrix_5x5)

5x5 random integer matrix:
 [[38 44 13  9 10]
 [12  6 16  1 17]
 [ 2 13  8 46  7]
 [26 21 38 19 21]
 [12 43 29 30 15]]


In [19]:
# Element in the 3rd row and 4th column (index 2, 3 since indexing starts at 0)
element = matrix_5x5[2, 3]
print("Element at 3rd row, 4th column:", element)

Element at 3rd row, 4th column: 46


In [20]:
# Last row and last column using negative indexing
last_row = matrix_5x5[-1]
last_column = matrix_5x5[:, -1]

print("Last row:", last_row)
print("Last column:", last_column)

Last row: [12 43 29 30 15]
Last column: [10 17  7 21 15]


In [21]:
# Change element at position (0,0) to 999 using indexing
matrix_5x5[0, 0] = 999
print("Updated matrix:\n", matrix_5x5)

Updated matrix:
 [[999  44  13   9  10]
 [ 12   6  16   1  17]
 [  2  13   8  46   7]
 [ 26  21  38  19  21]
 [ 12  43  29  30  15]]


## Task 7: Slicing

We build a 6×6 matrix containing numbers 1–36 in order, then use slicing to extract a sub-matrix, alternate rows/columns, and the bottom-right corner.

In [22]:
# 6x6 matrix with numbers 1 to 36 in order
matrix_6x6 = np.arange(1, 37).reshape(6, 6)
print("6x6 matrix:\n", matrix_6x6)

6x6 matrix:
 [[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]
 [31 32 33 34 35 36]]


In [23]:
# Top-left 3x3 sub-matrix
top_left_3x3 = matrix_6x6[0:3, 0:3]
print("Top-left 3x3 sub-matrix:\n", top_left_3x3)

Top-left 3x3 sub-matrix:
 [[ 1  2  3]
 [ 7  8  9]
 [13 14 15]]


In [24]:
# Every alternate row and every alternate column (step slicing)
alternate_rows_cols = matrix_6x6[::2, ::2]
print("Every alternate row and column:\n", alternate_rows_cols)

Every alternate row and column:
 [[ 1  3  5]
 [13 15 17]
 [25 27 29]]


In [25]:
# Last 2 rows and last 2 columns together as a single sub-matrix
last_2x2 = matrix_6x6[-2:, -2:]
print("Last 2 rows & last 2 columns sub-matrix:\n", last_2x2)

Last 2 rows & last 2 columns sub-matrix:
 [[29 30]
 [35 36]]


## Task 8: Random Matrices

We set a random seed, then generate decimal, integer, and standard-normal random matrices. We also demonstrate that fixing the seed and re-running the same code produces identical results.

In [26]:
np.random.seed(42)  # setting the seed

# 3x3 matrix of random decimals between 0 and 1
random_decimals = np.random.rand(3, 3)
print("Random decimals (0 to 1):\n", random_decimals)

Random decimals (0 to 1):
 [[0.37454012 0.95071431 0.73199394]
 [0.59865848 0.15601864 0.15599452]
 [0.05808361 0.86617615 0.60111501]]


In [27]:
# 3x3 matrix of random integers between 10 and 100
random_integers = np.random.randint(10, 101, size=(3, 3))
print("Random integers (10 to 100):\n", random_integers)

Random integers (10 to 100):
 [[33 12 31]
 [62 11 97]
 [39 47 11]]


In [28]:
# 4x4 matrix using the standard normal distribution (can include negative values)
standard_normal_matrix = np.random.randn(4, 4)
print("Standard normal distribution matrix:\n", standard_normal_matrix)

Standard normal distribution matrix:
 [[-0.46341769 -0.46572975  0.24196227 -1.91328024]
 [-1.72491783 -0.56228753 -1.01283112  0.31424733]
 [-0.90802408 -1.4123037   1.46564877 -0.2257763 ]
 [ 0.0675282  -1.42474819 -0.54438272  0.11092259]]


In [29]:
# Run the random decimal generation TWICE without changing the seed in between,
# but resetting the seed to the SAME value right before each run
np.random.seed(42)
run1 = np.random.rand(3, 3)

np.random.seed(42)
run2 = np.random.rand(3, 3)

print("Run 1:\n", run1)
print("Run 2:\n", run2)
print("Are both runs identical?", np.array_equal(run1, run2))

# Explanation: NumPy's random generator is actually a deterministic
# "pseudo-random" algorithm. Setting np.random.seed(42) resets the
# generator's internal starting state to a fixed point. Since both runs
# start from that exact same seed/state, they produce the exact same
# sequence of "random" numbers -- hence identical outputs.

Run 1:
 [[0.37454012 0.95071431 0.73199394]
 [0.59865848 0.15601864 0.15599452]
 [0.05808361 0.86617615 0.60111501]]
Run 2:
 [[0.37454012 0.95071431 0.73199394]
 [0.59865848 0.15601864 0.15599452]
 [0.05808361 0.86617615 0.60111501]]
Are both runs identical? True


## Task 9: Transpose

We create a 3×5 matrix of employee performance scores, transpose it, verify that a double transpose returns the original matrix, and use transpose to make a dot product between a 4×2 and 3×2 matrix possible.

In [30]:
# 3x5 matrix: rows = employees, columns = monthly performance scores
performance = np.array([
    [85, 90, 88, 92, 95],   # Employee 1
    [70, 75, 78, 80, 82],   # Employee 2
    [60, 65, 63, 70, 72]    # Employee 3
])

print("Original performance matrix:\n", performance)
print("Original shape:", performance.shape)

Original performance matrix:
 [[85 90 88 92 95]
 [70 75 78 80 82]
 [60 65 63 70 72]]
Original shape: (3, 5)


In [31]:
# Transpose the matrix
performance_T = performance.T
print("Transposed matrix:\n", performance_T)
print("New shape:", performance_T.shape)

Transposed matrix:
 [[85 70 60]
 [90 75 65]
 [88 78 63]
 [92 80 70]
 [95 82 72]]
New shape: (5, 3)


In [32]:
# Verify programmatically that transposing twice returns the original matrix
double_transpose = performance.T.T
is_same = np.array_equal(performance, double_transpose)
print("Does double transpose equal the original matrix?", is_same)

Does double transpose equal the original matrix? True


In [33]:
# Create a 4x2 and a 3x2 matrix
matrix_4x2 = np.array([
    [1, 2],
    [3, 4],
    [5, 6],
    [7, 8]
])

matrix_3x2 = np.array([
    [1, 0],
    [0, 1],
    [1, 1]
])

print("4x2 matrix:\n", matrix_4x2)
print("3x2 matrix:\n", matrix_3x2)

# matrix_4x2 (4x2) dot matrix_3x2 (3x2) is NOT valid directly, since inner
# dimensions (2 and 3) don't match. We transpose matrix_3x2 to make it 2x3,
# so that (4x2) dot (2x3) = (4x3), which is valid.
result = matrix_4x2.dot(matrix_3x2.T)
print("Dot product result (4x2 . (3x2)^T = 4x3):\n", result)
print("Result shape:", result.shape)

4x2 matrix:
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]
3x2 matrix:
 [[1 0]
 [0 1]
 [1 1]]
Dot product result (4x2 . (3x2)^T = 4x3):
 [[ 1  2  3]
 [ 3  4  7]
 [ 5  6 11]
 [ 7  8 15]]
Result shape: (4, 3)
